# Generated by Django 6.0.2 on 2026-02-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicaldata_purchaseorder_vendor_product_uom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='consumption',
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='sku',
            field=models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='core.product', to_field='sku'),
        ),
    ]
